# Generated by Django 4.2.2 on 2023-07-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
